AES cleanup fixes pt 1 for #179
GaloisInc/cryptol-specs pull request #210
Opened 2024-12-20 00:33 UTC by jn80842

Three of the tasks from issue 179, cleaning up small issues to do with the AES spec.

2024-12-20 17:15 UTC, marsella requested changes
This looks solid, thank you for addressing! I appreciate the coherent commits.

I have a few comments; the most important ones are about docs and naming in `SBox` -- the rest are mostly nitpicky.

One other top-level comments: please check off the boxes for the things you finished in #179!

2024-12-20 20:51 UTC, weaversa commented on Primitive/Symmetric/Cipher/Block/AES/ExpandKey.cry
> +SubWord [a0, a1, a2, a3] = [ Sbox::sbox a0, Sbox::sbox a1, Sbox::sbox a2, Sbox::sbox a3 ]
Have you considered `@@`?

2024-12-20 21:25 UTC, jn80842 commented on Primitive/Symmetric/Cipher/Block/AES/SBox.cry
> +sbox w = sboxTable @ w
Yeah, poor choice of variable name on my part.

2024-12-20 21:41 UTC, marsella commented on Primitive/Symmetric/Cipher/Block/AES/ExpandKey.cry
> +SubWord [a0, a1, a2, a3] = [ Sbox::sbox a0, Sbox::sbox a1, Sbox::sbox a2, Sbox::sbox a3 ]
I asked Lee to get as annoyingly close to the spec as possible :)
<img width="727" alt="image" src="https://github.com/user-attachments/assets/c518a994-e0a0-4eb6-baef-d5dc803a4076" />

Not the most elegant Cryptol, but hopefully anyone looking between the two lines should know they're the same.

2025-01-03 15:37 UTC, marsella approved these changes
Looks good, thank you!

2025-01-03 17:55 UTC, mccleeary-galois approved these changes

2025-01-03 17:56 UTC, merged